import Head from 'next/head';
// import { Roboto } from 'next/font/google';

// TODO: implementar essa fonte aqui
// const roboto = Roboto({ subsets: ['latin'], weight: "400", style: "normal" })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tsundoku</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1> -- TSUN V2 -- </h1>
      </main>
    </>
  );
}
